version: "3"
services:
  testing-mysql:
    image: mysql:8.0.23
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: board
      MYSQL_USER: boardadmin
      MYSQL_PASSWORD: 1234
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql