CREATE TABLE `user`
(
    `id` INT NOT NULL AUTO_INCREMENT,
    `userId` VARCHAR(45) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `nickName` VARCHAR(45) NOT NULL,
    `isAdmin` BOOLEAN NOT NULL DEFAULT 0,
    `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `isWithDraw` BOOLEAN NOT NULL DEFAULT 0,
    `status` ENUM('DEFAULT', 'ADMIN', 'DELETED') NOT NULL DEFAULT 'DEFAULT',
    `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);